### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by dvzrv** [moddevices/mod-lv2-extensions#1]
Hi! When packaging this for downstreams it would be very good to include a dedicated license file.
https://github.com/moddevices/mod-lv2-extensions/blob/60abe7176b4e4f46f20a41cdf3d65d909c8d8a34/mod-license.lv2/mod-license.h seems to be licensed under the terms of the ISC.

Are all files files in the repository covered by that license?

**Comment by falkTX** [comment]
Yes, we can assume that to be the case.

**Comment by falkTX** [comment]
Added a license file as per c65fdff4b07215d082643f3c2a918eb8283749c8

Wont do a release just yet, need to confirm the legal company name in written form first.

**Comment by falkTX** [comment]
PS: since I got your attention, FYI I got locked out of my own server while trying to ssh into it from a windows system... must be the fail2ban stuff, will try again later. I will not reply on IRC for the moment.

**Comment by falkTX** [comment]
License file is now part of 2022-09-25 release

**Comment by dvzrv** [comment]
Thanks! I pushed a package!
